# Generated by Django 4.0.7 on 2022-12-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
