# Generated by Django 4.0.7 on 2022-12-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_url',
            field=models.URLField(null=True),
        ),
    ]
