# Generated by Django 4.0.7 on 2022-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_film_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='homepage_slider_image',
            field=models.ImageField(null=True, upload_to='movies_prev_img'),
        ),
    ]
