# Generated by Django 4.0.7 on 2022-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_movie_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('movie', 'movie'), ('series', 'series')], max_length=10, null=True),
        ),
    ]
