# Generated by Django 4.1.4 on 2022-12-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_alter_movie_movie_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='genre',
        ),
    ]
