# Generated by Django 4.1.5 on 2023-01-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_customers_remove_comments_user_userlist_listedmovie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedmovie',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
        ),
    ]
