# Generated by Django 4.1.5 on 2023-01-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_listedmovie_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedmovie',
            name='customer',
        ),
    ]
