# Generated by Django 4.1.5 on 2023-01-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_customer_email_customer_name_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pictures/python_set_methods.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
