# Generated by Django 4.1.5 on 2023-01-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pictures/placeholder.png', null=True, upload_to='profile_pictures'),
        ),
    ]
